### ISSUE TITLE
AWS 서버 모듈 선정

### ISSUE THREAD

**Issue by hi-jason-jung** [hi-jason-jung/shopping-mall#10]
AWS 내 EC2, RDS, Amplify, IAM(Identity and Access Management),  API Gateway, Lambda 등 다양한 서비스를 제공하는 모듈들을 어떻게 활용할 것인가.

**Comment by hi-jason-jung** [comment]
본 프로젝트의 목적은 Cloud 사용에 대한 학습이 아닌 서버를 직접 구축해보는 것이 목적이므로 IaaS 급 모듈에 해당하는 EC2를 사용합니다. EC2 내에서 DB까지 구축 예정(필요하다면 RDS 정도는 따로 사용해 볼 수도 있음)

EC2 구축을 위한 참조 자료.
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/putty.html
https://velog.io/@rheey90/AWS-EC2-Node.js-%EC%84%9C%EB%B2%84-%EB%B0%B0%ED%8F%AC

**Comment by hi-jason-jung** [comment]
1. EC2 내 Ubuntu linux 18.04 버전으로 세팅 완료.   
2. 직접 EC2 클라우드 컴퓨팅을 위해서는 서버 생성시 발생하는 key-pair가 필요. 이를 이용하여 Putty 등 프로그램을 통해 SSH 접속 진행. 필요할 경우, Please contact to `hi-jason-jung`  
3. 현재 간단한 Node express 서버가 동작 중임. 3001 번 포트로 접속 시, 'Hello World!' 확인 가능. 자세한 IP 주소는 슬랙 참조.

**Comment by dolphin235** [comment]
Thank you for building the environment!
