### ISSUE TITLE
[Backend] DB 역할 분담

### ISSUE THREAD

**Issue by hi-jason-jung** [hi-jason-jung/shopping-mall#11]
DB를 기준으로 분담할 계획.

1. 유저 정보
2. 상품 정보

간단하게 위와 같은 2가지 DB를 구축할 예정. 구축하고 싶은 DB가 있으시면 Comment 달아주세요.

**Comment by dolphin235** [comment]
how do you plan to use which DB framework?

**Comment by dolphin235** [comment]
I think we need to make a list of what we will make.
plus the structure of services ?!

**Comment by hi-jason-jung** [comment]
<Architecture>

Frontend - (정: 이상호, 부: 정은식)
- HTML, CSS, JS
- FW: ReactJS

Backend - (정: 정은식, 부: 이상호)
- NodeJS
- DB: MongoDB, MySQL, Docker

**Comment by dolphin235** [comment]
Good!
