### ISSUE TITLE
Cloud Platform 선정

### ISSUE THREAD

**Issue by hi-jason-jung** [hi-jason-jung/shopping-mall#2]
대표 클라우드 플랫폼 3사 중 선택 예정.

AWS
- 장점: 수치, 모니터링, 보안 등 많은 기능 제공. 기업 친화적인 서비스 제공. 오픈되어있고 매우 유연함, 세계적으로 점유율이 가장 높음.
- 단점: 사용하기 어려움. 너무나 많은 옵션. 비용 관리
- Market share: 62%
 
Azure
- 장점: MS tools들과 연동, 광범위한 피처 셋, 오픈 소스 지원, 하이브리드 클라우드, Ranks first in development and testing tools.
- 단점: Management tool 의 효율성이 떨어짐. Less "enterprize-ready"
- Market share: 20%

GCP
- 장점:  오픈 소스 지원, Discounts & flexible contracts, 비즈니스 서비스 기반 디자인, DevOps expertise
- 단점: IaaS market에 최근 진입. Data center가 상대적으로 부족. 상대적으로 부족한 서비스 및 피처
- Market share: 12%

Reference: 
- https://brunch.co.kr/@topasvga/1242
- https://judo0179.tistory.com/115

**Comment by hi-jason-jung** [comment]
압도적인 Market share와 많은 Reference가 존재한다는 2가지 이유만으로 AWS를 쓸 이유는 충분하다고 봅니다. 이견 없으시면 Amazon의 AWS로 가닥을 잡으려고 합니다. 의견 부탁드려요.

**Comment by dolphin235** [comment]
For now, using AWS is good because our goal is to study.
AWS is the most common platform we can choose.
If we encounter the limitation with AWS, discuss about platform again.

**Comment by hi-jason-jung** [comment]
Thank you for your answer. Then let's talk about how we construct architecture in AWS.

**Comment by hi-jason-jung** [comment]
AWS selected
